// Merge recipes.base.json + packs.json -> site/js/data.js  (window.ALMANAC)
// If packs.json is missing, fills light placeholders so the UI still renders.
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const base = JSON.parse(fs.readFileSync(path.join(ROOT, 'site/data/recipes.base.json'), 'utf8'));
let packs = [];
const packPath = path.join(ROOT, 'site/data/packs.json');
if (fs.existsSync(packPath)) {
  const raw = JSON.parse(fs.readFileSync(packPath, 'utf8'));
  packs = Array.isArray(raw) ? raw : (raw.packs || []);
}
const byId = Object.fromEntries(packs.map(p => [p.id, p]));

// base spirit -> family (for filtering) + family label
const FAMILY = {
  '金酒': ['gin', '金酒 Gin'],
  '伏特加': ['vodka', '伏特加 Vodka'],
  '朗姆酒': ['rum', '朗姆酒 Rum'],
  '白朗姆酒': ['rum', '朗姆酒 Rum'],
  '卡莎萨': ['rum', '卡莎萨 Cachaça'],
  '威士忌': ['whisky', '威士忌 Whisky'],
  '黑麦威士忌': ['whisky', '威士忌 Whisky'],
  '龙舌兰': ['tequila', '龙舌兰 Tequila'],
  '白兰地': ['brandy', '白兰地 Brandy'],
  '金巴利': ['bitter', '餐前苦酒 Aperitivo'],
};

const merged = base.map((b, i) => {
  const p = byId[b.id] || {};
  const fam = FAMILY[b.base] || ['other', b.base];
  return {
    id: b.id, en: b.en, cn: b.cn, base: b.base, baseEn: b.baseEn,
    family: fam[0], familyLabel: fam[1],
    card: `assets/cards/${b.id}.jpg`,
    illu: `assets/illustrations/${b.id}.png`,
    ingredients: b.ingredients,
    steps: b.steps,
    tagline: p.tagline || '',
    // some agents emitted literal "\n" — normalise to real newlines for paragraphs
    story: (p.story || '').replace(/\\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim(),
    flavorTags: p.flavorTags || [],
    palate: p.palate || '', aroma: p.aroma || '',
    glass: p.glass || '', garnish: p.garnish || '',
    method: p.method || '', strength: p.strength || 3,
    abv: p.abv || '', difficulty: p.difficulty || 1,
    prepTime: p.prepTime || '', bestTime: p.bestTime || '',
    note: p.note || '', imagePrompt: p.imagePrompt || '',
    index: i + 1,
  };
});

const out = '/* auto-generated by work/merge.js — do not edit by hand */\n' +
  'window.ALMANAC = ' + JSON.stringify(merged, null, 1) + ';\n';
fs.writeFileSync(path.join(ROOT, 'site/js/data.js'), out);
const enriched = merged.filter(m => m.story).length;
console.log(`wrote site/js/data.js — ${merged.length} cocktails, ${enriched} enriched, ${packs.length} packs`);
